### ISSUE TITLE
Pogo Pin Size

### ISSUE THREAD

**Issue by kontakt** [sparkfun/ISP_Pogo_Board#1]
What size pogo pins are used with this design?

**Comment by bboyho** [comment]
Hi!

Sorry, I just noticed this question when updating the repo.  These use the pointed tip pogo pins and they should be linked on the product page. If you have not already, make sure to check out the [product page for the pointed tip pogo pin](https://www.sparkfun.com/products/9174) for the dimensional drawing and measurements. According to the product page:

> * Length: 1.3" (33mm)
> * Travel: 1/4" (6.5mm)
> * Head size 0.05" (1.3mm)

These can be used with standard 0.1"-spaced PTHs.
